config/routes.rb
Form::Application.routes.draw do
  devise_for :users

  resources :sampleforms

end

app/models/sampleform.rb
class Sampleform < ActiveRecord::Base
  attr_accessible :A, :Ans, :B, :C, :D, :Level, :Question, :Subj
  validates Question, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/sampleforms_controller.rb
class SampleformsController < ApplicationController

  def index
    @sampleforms= Sampleform.all
  end


  def new
    @sampleforms = Sampleform.new
  end


  def create
    @sampleforms = Sampleform.new(params[:sampleform])
    if@sampleforms.save
      redirect_to sampleforms_path
    end
  end

  def destroy
    @sampleforms = Sampleform.find(params[:id])
    if @sampleforms.present?
      @sampleforms.destroy
    end
    redirect_to sampleforms_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sampleforms_helper.rb
module SampleformsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Form</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<p class="navbar-text pull-right">
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>



    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>


<%= yield %>

</body>
</html>

app/views/sampleforms/_form.html.erb
<%= form_for @sampleforms do |f| %>

    <div class="first">
        <%= f.label :Question %>
        <%= f.text_field :Question %>
    </div>

    <div class="second">
        <%= f.label :A %>
        <%= f.text_field :A %>

        <%= f.label :B %>
        <%= f.text_field :B %>
    </div>

    <div class="second">
        <%= f.label :C %>
        <%= f.text_field :C %>

        <%= f.label :D %>
        <%= f.text_field :D %>
    </div>

    <div class="third">
        <%= f.label :Answer %>
        <%= f.text_field :Ans %>
    </div>

    <div class="third">
        <%= f.label :Level %>
        <%= f.radio_button :Level,'Easy', :checked => true %>Easy
        <%= f.radio_button :Level, 'Hard' %>Hard


        <%= f.label :Subjects %>
        <%= f.select :Subj, [['Biology','Biology'],['Chemistry','Chemistry'],['Maths','Maths'],['Physics','Physics']] %>
    </div>

    <p>
        <%= f.submit "Submit" %>
    </p>




<% end %>

app/views/sampleforms/index.html.erb
<%= link_to "Enter the Question", new_sampleform_path %> <b/>
<table border="1">
    <thead>
    <tr>
        <th>Question</th>
        <th>A</th>
        <th>B</th>
        <th>C</th>
        <th>D</th>
        <th>Answer</th>
        <th>level</th>
        <th>Subjects</th>
    </tr>
    </thead>
    <tbody>
    <%= @sampleforms.each do |sampleform| %>
        <tr>
            <td><%= sampleform.Question %></td>
            <td><%= sampleform.A %></td>
            <td><%= sampleform.B %></td>
            <td><%= sampleform.C %></td>
            <td><%= sampleform.D %></td>
            <td><%= sampleform.Ans %></td>
            <td><%= sampleform.Level %></td>
            <td><%= sampleform.Subj %></td>
            <td></td>

            <td><%= link_to "Delete", sampleform, method: :delete, data: {:confirm=>"Are you sure ? "} %></td>

        </tr>

    <% end %>

    </tbody>

</table>

app/views/sampleforms/new.html.erb
<%= render :partial => "form" %>